// Generated TypeScript types for EduCanvas Database Schema v4.1
// Auto-generated on: 2025-08-10
// DO NOT EDIT THIS FILE MANUALLY - Use supabase gen types command

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Database Enums
export type UserStatus = 'active' | 'inactive' | 'suspended' | 'pending_approval'
export type StudentStatus = 'active' | 'inactive' | 'graduated' | 'withdrawn' | 'suspended'
export type BillingType = 'monthly' | 'sessions' | 'hours' | 'package' | 'drop_in'
export type DiscountType = 'sibling' | 'early_payment' | 'loyalty' | 'scholarship' | 'promotion' | 'volume'
export type SalaryPolicyType = 'fixed_monthly' | 'fixed_hourly' | 'commission' | 'tiered_commission' | 'student_based' | 'hybrid' | 'guaranteed_minimum'
export type AttendanceStatus = 'present' | 'absent' | 'late' | 'excused'
export type PaymentStatus = 'pending' | 'completed' | 'overdue' | 'cancelled' | 'refunded'
export type ClassroomStatus = 'available' | 'occupied' | 'maintenance' | 'reserved'
export type ClassroomType = 'general' | 'lab' | 'seminar' | 'lecture_hall' | 'study_room'
export type ScheduleStatus = 'active' | 'cancelled' | 'rescheduled' | 'completed'
export type ExamType = 'midterm' | 'final' | 'quiz' | 'mock_exam' | 'placement_test' | 'progress_test'
export type QuestionType = 'multiple_choice' | 'short_answer' | 'essay' | 'true_false' | 'fill_blank'
export type DocumentType = 'exam' | 'homework' | 'handout' | 'answer_key' | 'curriculum' | 'report' | 'other'
export type FileStatus = 'uploading' | 'active' | 'archived' | 'deleted'
export type HistoryAction = 'create' | 'update' | 'delete' | 'move' | 'enroll' | 'withdraw' | 'payment' | 'exam' | 'consultation'
export type ConsultationStatus = 'scheduled' | 'completed' | 'cancelled' | 'no_show'
export type ConsultationType = 'enrollment' | 'academic' | 'behavioral' | 'career' | 'parent_meeting' | 'follow_up'

// Video System Enums (v4.1)
export type VideoStatus = 'draft' | 'published' | 'private' | 'archived' | 'deleted'
export type VideoType = 'lecture' | 'supplement' | 'homework_review' | 'exam_review' | 'announcement'
export type WatchStatus = 'not_started' | 'in_progress' | 'completed' | 'skipped'
export type VideoQuality = '240p' | '360p' | '480p' | '720p' | '1080p' | '1440p' | '2160p'

export type Database = {
  public: {
    Tables: {
      // ================================================================
      // Multitenant Core Tables
      // ================================================================
      tenants: {
        Row: {
          id: string
          name: string
          slug: string
          domain: string | null
          contact_email: string | null
          contact_phone: string | null
          address: string | null
          business_registration: string | null
          settings: Json
          features: Json
          limits: Json
          subscription_tier: string
          subscription_status: string
          trial_ends_at: string | null
          billing_email: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          domain?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          address?: string | null
          business_registration?: string | null
          settings?: Json
          features?: Json
          limits?: Json
          subscription_tier?: string
          subscription_status?: string
          trial_ends_at?: string | null
          billing_email?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          slug?: string
          domain?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          address?: string | null
          business_registration?: string | null
          settings?: Json
          features?: Json
          limits?: Json
          subscription_tier?: string
          subscription_status?: string
          trial_ends_at?: string | null
          billing_email?: string | null
          is_active?: boolean
          updated_at?: string
        }
      }

      tenant_roles: {
        Row: {
          id: string
          tenant_id: string
          name: string
          display_name: string
          description: string | null
          parent_role_id: string | null
          hierarchy_level: number
          base_permissions: Json
          is_system_role: boolean
          is_assignable: boolean
          max_users: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          display_name: string
          description?: string | null
          parent_role_id?: string | null
          hierarchy_level?: number
          base_permissions?: Json
          is_system_role?: boolean
          is_assignable?: boolean
          max_users?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          display_name?: string
          description?: string | null
          parent_role_id?: string | null
          hierarchy_level?: number
          base_permissions?: Json
          is_system_role?: boolean
          is_assignable?: boolean
          max_users?: number | null
          updated_at?: string
        }
      }

      permissions: {
        Row: {
          id: string
          resource: string
          action: string
          scope: string
          name: string
          description: string | null
          category: string | null
          is_system_permission: boolean
          requires_approval: boolean
          created_at: string
        }
        Insert: {
          id?: string
          resource: string
          action: string
          scope: string
          name: string
          description?: string | null
          category?: string | null
          is_system_permission?: boolean
          requires_approval?: boolean
          created_at?: string
        }
        Update: {
          resource?: string
          action?: string
          scope?: string
          name?: string
          description?: string | null
          category?: string | null
          is_system_permission?: boolean
          requires_approval?: boolean
        }
      }

      tenant_users: {
        Row: {
          id: string
          tenant_id: string
          user_id: string
          role_id: string | null
          custom_permissions: Json
          status: UserStatus
          invited_by: string | null
          invited_at: string | null
          joined_at: string | null
          last_login_at: string | null
          last_activity_at: string | null
          login_attempts: number
          locked_until: string | null
          two_factor_enabled: boolean
          two_factor_secret: string | null
          backup_codes: string[] | null
          session_timeout_minutes: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          user_id: string
          role_id?: string | null
          custom_permissions?: Json
          status?: UserStatus
          invited_by?: string | null
          invited_at?: string | null
          joined_at?: string | null
          last_login_at?: string | null
          last_activity_at?: string | null
          login_attempts?: number
          locked_until?: string | null
          two_factor_enabled?: boolean
          two_factor_secret?: string | null
          backup_codes?: string[] | null
          session_timeout_minutes?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          role_id?: string | null
          custom_permissions?: Json
          status?: UserStatus
          invited_by?: string | null
          invited_at?: string | null
          joined_at?: string | null
          last_login_at?: string | null
          last_activity_at?: string | null
          login_attempts?: number
          locked_until?: string | null
          two_factor_enabled?: boolean
          two_factor_secret?: string | null
          backup_codes?: string[] | null
          session_timeout_minutes?: number | null
          updated_at?: string
        }
      }

      // ================================================================
      // Business Logic Tables
      // ================================================================
      instructors: {
        Row: {
          id: string
          tenant_id: string
          user_id: string | null
          name: string
          phone: string | null
          email: string | null
          specialization: string | null
          qualification: string | null
          bank_account: string | null
          status: StudentStatus
          hire_date: string
          memo: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          user_id?: string | null
          name: string
          phone?: string | null
          email?: string | null
          specialization?: string | null
          qualification?: string | null
          bank_account?: string | null
          status?: StudentStatus
          hire_date?: string
          memo?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          user_id?: string | null
          name?: string
          phone?: string | null
          email?: string | null
          specialization?: string | null
          qualification?: string | null
          bank_account?: string | null
          status?: StudentStatus
          hire_date?: string
          memo?: string | null
          updated_at?: string
        }
      }

      classes: {
        Row: {
          id: string
          tenant_id: string
          name: string
          subject: string | null
          grade_level: string | null
          max_students: number
          current_students: number
          instructor_id: string | null
          classroom: string | null
          color: string
          status: StudentStatus
          order_index: number
          start_date: string | null
          end_date: string | null
          memo: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          subject?: string | null
          grade_level?: string | null
          max_students?: number
          current_students?: number
          instructor_id?: string | null
          classroom?: string | null
          color?: string
          status?: StudentStatus
          order_index?: number
          start_date?: string | null
          end_date?: string | null
          memo?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          subject?: string | null
          grade_level?: string | null
          max_students?: number
          current_students?: number
          instructor_id?: string | null
          classroom?: string | null
          color?: string
          status?: StudentStatus
          order_index?: number
          start_date?: string | null
          end_date?: string | null
          memo?: string | null
          updated_at?: string
        }
      }

      students: {
        Row: {
          id: string
          tenant_id: string
          name: string
          phone: string | null
          parent_name: string | null
          parent_phone: string
          grade: string | null
          class_id: string | null
          status: StudentStatus
          enrollment_date: string
          graduation_date: string | null
          position_in_class: number
          display_color: string | null
          memo: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          phone?: string | null
          parent_name?: string | null
          parent_phone: string
          grade?: string | null
          class_id?: string | null
          status?: StudentStatus
          enrollment_date?: string
          graduation_date?: string | null
          position_in_class?: number
          display_color?: string | null
          memo?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          phone?: string | null
          parent_name?: string | null
          parent_phone?: string
          grade?: string | null
          class_id?: string | null
          status?: StudentStatus
          enrollment_date?: string
          graduation_date?: string | null
          position_in_class?: number
          display_color?: string | null
          memo?: string | null
          updated_at?: string
        }
      }

      course_packages: {
        Row: {
          id: string
          tenant_id: string
          class_id: string
          name: string
          billing_type: BillingType
          price: number
          sessions_count: number | null
          hours_count: number | null
          validity_days: number | null
          max_monthly_sessions: number | null
          discount_type: DiscountType | null
          discount_value: number | null
          auto_extend: boolean
          status: StudentStatus
          description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          class_id: string
          name: string
          billing_type: BillingType
          price: number
          sessions_count?: number | null
          hours_count?: number | null
          validity_days?: number | null
          max_monthly_sessions?: number | null
          discount_type?: DiscountType | null
          discount_value?: number | null
          auto_extend?: boolean
          status?: StudentStatus
          description?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          class_id?: string
          name?: string
          billing_type?: BillingType
          price?: number
          sessions_count?: number | null
          hours_count?: number | null
          validity_days?: number | null
          max_monthly_sessions?: number | null
          discount_type?: DiscountType | null
          discount_value?: number | null
          auto_extend?: boolean
          status?: StudentStatus
          description?: string | null
          updated_at?: string
        }
      }

      // ================================================================
      // YouTube Video System Tables (v4.1)
      // ================================================================
      youtube_videos: {
        Row: {
          id: string
          tenant_id: string
          youtube_id: string
          title: string
          description: string | null
          duration: number
          thumbnail_url: string | null
          channel_id: string
          published_at: string
          category: string | null
          tags: string[]
          quality_levels: VideoQuality[]
          captions_available: boolean
          instructor_id: string | null
          class_id: string | null
          video_type: VideoType
          status: VideoStatus
          view_count: number
          like_count: number | null
          dislike_count: number | null
          privacy_level: string
          is_age_restricted: boolean
          upload_date: string | null
          last_updated: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          youtube_id: string
          title: string
          description?: string | null
          duration: number
          thumbnail_url?: string | null
          channel_id: string
          published_at: string
          category?: string | null
          tags?: string[]
          quality_levels?: VideoQuality[]
          captions_available?: boolean
          instructor_id?: string | null
          class_id?: string | null
          video_type?: VideoType
          status?: VideoStatus
          view_count?: number
          like_count?: number | null
          dislike_count?: number | null
          privacy_level?: string
          is_age_restricted?: boolean
          upload_date?: string | null
          last_updated?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string
          description?: string | null
          duration?: number
          thumbnail_url?: string | null
          category?: string | null
          tags?: string[]
          quality_levels?: VideoQuality[]
          captions_available?: boolean
          instructor_id?: string | null
          class_id?: string | null
          video_type?: VideoType
          status?: VideoStatus
          view_count?: number
          like_count?: number | null
          dislike_count?: number | null
          privacy_level?: string
          is_age_restricted?: boolean
          upload_date?: string | null
          last_updated?: string | null
          metadata?: Json
          updated_at?: string
        }
      }

      student_video_progress: {
        Row: {
          id: string
          tenant_id: string
          student_id: string
          video_id: string
          watched_duration: number
          total_duration: number
          completion_percentage: number
          last_watched_at: string
          completed_at: string | null
          watch_sessions: Json[]
          notes: string | null
          quality_watched: VideoQuality | null
          watch_speed: number
          pause_count: number
          rewind_count: number
          forward_count: number
          full_screen_duration: number | null
          device_type: string | null
          browser_type: string | null
          ip_address: string | null
          location_info: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          student_id: string
          video_id: string
          watched_duration?: number
          total_duration: number
          completion_percentage?: number
          last_watched_at: string
          completed_at?: string | null
          watch_sessions?: Json[]
          notes?: string | null
          quality_watched?: VideoQuality | null
          watch_speed?: number
          pause_count?: number
          rewind_count?: number
          forward_count?: number
          full_screen_duration?: number | null
          device_type?: string | null
          browser_type?: string | null
          ip_address?: string | null
          location_info?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          watched_duration?: number
          total_duration?: number
          completion_percentage?: number
          last_watched_at?: string
          completed_at?: string | null
          watch_sessions?: Json[]
          notes?: string | null
          quality_watched?: VideoQuality | null
          watch_speed?: number
          pause_count?: number
          rewind_count?: number
          forward_count?: number
          full_screen_duration?: number | null
          device_type?: string | null
          browser_type?: string | null
          ip_address?: string | null
          location_info?: Json | null
          updated_at?: string
        }
      }

      video_assignments: {
        Row: {
          id: string
          tenant_id: string
          class_id: string
          video_id: string
          instructor_id: string
          title: string
          description: string | null
          assigned_at: string
          due_date: string | null
          required_completion_percentage: number
          is_mandatory: boolean
          allow_speed_change: boolean
          allow_seeking: boolean
          max_attempts: number | null
          time_limit_minutes: number | null
          status: ScheduleStatus
          completion_reward_points: number | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          class_id: string
          video_id: string
          instructor_id: string
          title: string
          description?: string | null
          assigned_at?: string
          due_date?: string | null
          required_completion_percentage?: number
          is_mandatory?: boolean
          allow_speed_change?: boolean
          allow_seeking?: boolean
          max_attempts?: number | null
          time_limit_minutes?: number | null
          status?: ScheduleStatus
          completion_reward_points?: number | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string
          description?: string | null
          assigned_at?: string
          due_date?: string | null
          required_completion_percentage?: number
          is_mandatory?: boolean
          allow_speed_change?: boolean
          allow_seeking?: boolean
          max_attempts?: number | null
          time_limit_minutes?: number | null
          status?: ScheduleStatus
          completion_reward_points?: number | null
          metadata?: Json
          updated_at?: string
        }
      }

      // ================================================================
      // Audit and Backup Tables
      // ================================================================
      audit_logs: {
        Row: {
          id: string
          tenant_id: string
          user_id: string | null
          table_name: string
          record_id: string | null
          action: string
          old_values: Json | null
          new_values: Json | null
          changed_columns: string[] | null
          ip_address: string | null
          user_agent: string | null
          session_id: string | null
          request_id: string | null
          occurred_at: string
          application_name: string | null
          risk_level: string
          is_anomalous: boolean
          audit_date: string
        }
        Insert: {
          id?: string
          tenant_id: string
          user_id?: string | null
          table_name: string
          record_id?: string | null
          action: string
          old_values?: Json | null
          new_values?: Json | null
          changed_columns?: string[] | null
          ip_address?: string | null
          user_agent?: string | null
          session_id?: string | null
          request_id?: string | null
          occurred_at?: string
          application_name?: string | null
          risk_level?: string
          is_anomalous?: boolean
        }
        Update: {
          table_name?: string
          record_id?: string | null
          action?: string
          old_values?: Json | null
          new_values?: Json | null
          changed_columns?: string[] | null
          ip_address?: string | null
          user_agent?: string | null
          session_id?: string | null
          request_id?: string | null
          occurred_at?: string
          application_name?: string | null
          risk_level?: string
          is_anomalous?: boolean
        }
      }
    }

    Views: {
      // Student enrollment statistics view
      student_enrollment_stats: {
        Row: {
          tenant_id: string
          student_id: string
          student_name: string
          class_name: string | null
          total_enrollments: number
          active_enrollments: number
          completed_enrollments: number
          total_payments: number | null
          last_payment_date: string | null
          enrollment_status: StudentStatus
        }
      }

      // Video learning analytics view
      video_learning_analytics: {
        Row: {
          tenant_id: string
          video_id: string
          video_title: string
          instructor_name: string | null
          class_name: string | null
          total_students: number
          completed_students: number
          average_completion: number
          total_watch_time: number
          average_watch_time: number
          most_watched_section: Json | null
          completion_rate: number
          engagement_score: number
        }
      }

      // Class performance analytics view
      class_performance_analytics: {
        Row: {
          tenant_id: string
          class_id: string
          class_name: string
          instructor_name: string | null
          total_students: number
          total_videos: number
          average_video_completion: number
          total_watch_hours: number
          most_active_students: Json[]
          performance_trend: Json
          last_updated: string
        }
      }
    }

    Functions: {
      // Get student by tenant
      get_student_by_tenant: {
        Args: { 
          p_tenant_id: string
          p_student_id: string 
        }
        Returns: Database['public']['Tables']['students']['Row'] | null
      }

      // Update video progress
      update_video_progress: {
        Args: {
          p_tenant_id: string
          p_student_id: string
          p_video_id: string
          p_watched_duration: number
          p_session_data: Json
        }
        Returns: boolean
      }

      // Get video assignments for student
      get_student_video_assignments: {
        Args: {
          p_tenant_id: string
          p_student_id: string
          p_class_id?: string
        }
        Returns: Database['public']['Tables']['video_assignments']['Row'][]
      }

      // Calculate video completion rate
      calculate_video_completion_rate: {
        Args: {
          p_tenant_id: string
          p_video_id: string
        }
        Returns: number
      }

      // Get tenant analytics
      get_tenant_analytics: {
        Args: {
          p_tenant_id: string
          p_start_date?: string
          p_end_date?: string
        }
        Returns: Json
      }

      // Backup tenant data
      backup_tenant_data: {
        Args: {
          p_tenant_id: string
          p_backup_type: string
        }
        Returns: Json
      }

      // Restore tenant data
      restore_tenant_data: {
        Args: {
          p_tenant_id: string
          p_backup_id: string
        }
        Returns: boolean
      }
    }

    Enums: {
      user_status: UserStatus
      student_status: StudentStatus
      billing_type: BillingType
      discount_type: DiscountType
      salary_policy_type: SalaryPolicyType
      attendance_status: AttendanceStatus
      payment_status: PaymentStatus
      classroom_status: ClassroomStatus
      classroom_type: ClassroomType
      schedule_status: ScheduleStatus
      exam_type: ExamType
      question_type: QuestionType
      document_type: DocumentType
      file_status: FileStatus
      history_action: HistoryAction
      consultation_status: ConsultationStatus
      consultation_type: ConsultationType
      video_status: VideoStatus
      video_type: VideoType
      watch_status: WatchStatus
      video_quality: VideoQuality
    }
  }
}